version: "3.7"
services:
  postgres:
    image: postgres
    container_name: postgres-db
    environment:
      POSTGRES_DB: swe304
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 10s
      timeout: 5s
      retries: 5

  web:
    image: abdulhady/swe304-project3-web
    container_name: web
    ports:
      - "8082:8081"
    depends_on:
      - postgres
    volumes:
      - ./src/main/resources/static/images:/src/main/resources/static/images
    environment:
      DB_URL: jdbc:postgresql://postgres
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres


volumes:
  pgdata:
  images:

networks:
  web:
  postgres: